# Generated by Django 6.0.2 on 2026-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('datebirth', models.DateField()),
                ('interests', models.JSONField()),
            ],
        ),
    ]
