# Generated by Django 6.0.2 on 2026-02-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='datebirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='interests',
            field=models.JSONField(null=True),
        ),
    ]
